insert into location values(1, '유스페이스 1A동', '1');
insert into location values(2, '유스페이스 1B동', '1');
insert into location values(3, '유스페이스 2A동', '1');
insert into location values(4, '유스페이스 2B동', '1');
insert into location values(5, 'H스퀘어 N동', '1');
insert into location values(6, 'H스퀘어 S동', '1');
insert into location values(7, '삼환하이펙스 A동', '1');
insert into location values(8, '삼환하이펙스 B동', '1');
insert into location values(9, '아브뉴프랑', '1');
insert into location values(10, '유스페이스 2B동', '2');